//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iron.GPS.Repositories.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetGroup
    {
        public AssetGroup()
        {
            this.Asset = new HashSet<Asset>();
        }
    
        public System.Guid AssetGroupId { get; set; }
        public Nullable<System.Guid> ParentAssetGroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
    
        public virtual ICollection<Asset> Asset { get; set; }
    }
}
