//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iron.GPS.Repositories.Provider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IronGPSEntities : DbContext
    {
        public IronGPSEntities()
            : base("name=IronGPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Asset { get; set; }
        public virtual DbSet<AssetGroup> AssetGroup { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User2Asset> User2Asset { get; set; }
    }
}
