//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iron.GPS.Repositories.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.User1 = new HashSet<User>();
        }
    
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> ParentUserId { get; set; }
        public string LoginName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Tel { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<int> LimitedSubUserCount { get; set; }
        public Nullable<int> LimitedAssetCount { get; set; }
        public Nullable<bool> IsAliasUser { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
    
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
